### ISSUE TITLE
webnovel login

### ISSUE THREAD

**Issue by cosmosg9** [mHaisham/novelsave#18]
How do I use the login in webnovel account. Also, can I get privileged chapters also if I have purchased a privileged on my website novel account and locked them?

**Comment by mHaisham** [comment]
I'm sorry to say that webnovel login isnt available ever since v0.5.8 #15
I plan to add back the login feature in v0.6.1, however it wont be available for atleast a week

if you want to use it you may **downgrade to v0.5.7 and below**

```
py -m pip install novelsave==0.5.7
```

then you may use the command

```
novelsave [webnovel_url] -u -p -c --email [email]
```

it would ask for password, also note that, you would need argument **email** for commands `u` and `p`

- privileged chapters that are purchased would be available

**Comment by cosmosg9** [comment]
thanks, I'll be waiting for you to fix this.
Also, do you have any Patreon or ko-fi, etc?

**Comment by mHaisham** [comment]
I don't have a patreon or a ko-fi account.
Thank you for your thought.
